## Uses of Numpy

### 1)Arithmatic operations
### 2)Stastical operations
### 3)Bitwise operations
### 4)Copying & viewing arrays
### 5)Stacking 
### 6)Matrix operations
### 7)Linesr Algebra
### 8)Broadcasting
### 9)Mathematical operations 
### 10)Searching,sorting & counting

# 1.Array Cration Functions

In [39]:
import numpy as np

In [40]:
# Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [41]:
b = np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [42]:
c = np.linspace(0,1,5)
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [43]:
d = np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [44]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [45]:
 f = np.eye(4)
print("Identify matrix f:\n",f)
            

Identify matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2.Array Manipulation Functions

In [46]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [47]:
# Flatten an array
f1 = np.array([[1,2],[3,4]])
flattend = np.ravel(f1)
print("Flattend array:",flattend)

Flattend array: [1 2 3 4]


In [48]:
# Transpose an array:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [49]:
# Stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2, b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3.Mathematical Functions

In [50]:
# Add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2)
print("added 2 to g:",added)


added 2 to g: [3 4 5 6]


In [51]:
# Square each element
squared = np.power(g,2)
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [52]:
# Square root of each element
sqrt_val = np.sqrt(g)
print("square root of g:",sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [53]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [54]:
# Dot product of two arrays
a2 = np.array([1,2,3])
dot_product = np.dot(a2,g)
print("Dot product of a and g:",dot_Product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [55]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [56]:
a3 = np.array([1,2,3,])
dot_product = np.dot(a1, a)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# 4.Statical Functions

In [57]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [58]:
# Standard deviation of an array
std_dev = np.std(s)
print("standard deviation of s:",std_dev)

standard deviation of s: 1.118033988749895


In [59]:
# Minimum elment of array
minimum = np.min(s)
print("min of s:",minimum)

min of s: 1


In [60]:
# Maximum element of an array
maximum = np.max(s)
print("max of s:",maximum)

max of s: 4


# 5.Linear Algebra Functions

In [61]:
# create a matrix 
matrix = np.array([[1,2],[3,4]])

In [62]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:",determinant)

Determinant of matrix: -2.0000000000000004


In [64]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n",inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6.Random Sampling Functions

In [66]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.8046388  0.79966832 0.45520356]


In [67]:
# set seed for reproducibility
np.random.seed(0)
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [68]:
# Generate random integers
rand_ints = np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [3 7 9 3 5]


In [72]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7.Boolean & Logical Functions

In [73]:
# Check all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [75]:
# check if all elements are true
logical_test = np.array([False,False,False])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [76]:
# Check if any elements are True
# any 
any_true = np.any(logical_test)
print("Any elements True:",any_true)

Any elements True: False


# 8.Set Operations

In [78]:
# Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [79]:
# Union of two arrays
union = np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# 9.Array Attribute Functions

In [83]:
# Array attributes
a = np.array([1,2,3])
shape = a.shape
size = a.size
dimensions = a.ndim
dtype = a.dtype

print("Shape of a:",shape)
print("Shape of a:",size)
print("Number of diamensions of a:",dimensions)
print("Data type of a:",dtype)

Shape of a: (3,)
Shape of a: 3
Number of diamensions of a: 1
Data type of a: int32


# 10.Other Functions

In [84]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [85]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [86]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
